import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import "swiper/css";
import Header from "@/components/mainLayout/header/Header";
import Footer from "@/components/mainLayout/footer/Footer";
import QueryProvider from "@/provider/QueryProvider";

export const metadata: Metadata = {
  title: "Movie Site",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin", "cyrillic"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <QueryProvider>
          <Header />
          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
